---
roles:
  base:
    private_networks:
      - ip: '0.0.0.0'
        auto_network: true
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts

  posix_agent:
    provisioners:
      - type: shell
        inline: |-
          curl -sk https://master.puppetlabs.demo:8140/packages/current/install.bash | /bin/bash 

  puppet_master:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 4096]
        - [modifyvm, !ruby/sym id, '--ioapic', 'on']
        - [modifyvm, !ruby/sym id, '--cpus', '4']
    provisioners:
      - type: pe_bootstrap
        role: !ruby/sym master
        autosign:
          - jenkins.puppetlabs.demo
          - slave1.puppetlabs.demo
          - gitlab.puppetlabs.demo
      - type: shell
        path: provision/bootstrap_puppet_master.sh
      - type: shell
        path: provision/set_server_role.sh
        args: 'role::puppet::master'

  jenkins_master:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]
        - [modifyvm, !ruby/sym id, '--ioapic', 'on']
        - [modifyvm, !ruby/sym id, '--cpus', '2']
    provisioners:
      - type: shell
        path: provision/set_server_role.sh
        args:
          - '-w' 
          - 'role::jenkins::master'

  jenkins_slave:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 512]
        - [modifyvm, !ruby/sym id, '--ioapic', 'on']
    provisioners:
      - type: shell
        path: provision/set_server_role.sh
        args:
          - '-w' 
          - 'role::jenkins::slave'

  gitlab_server:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 512]
        - [modifyvm, !ruby/sym id, '--ioapic', 'on']
    provisioners:
      - type: shell
        path: provision/set_server_role.sh
        args:
          - '-w' 
          - 'role::gitlab'
