---
vms:
  - name: "master.puppetlabs.demo"
    box:  "puppetlabs/centos-6.5-64-nocm"
    roles: 
      - "puppet_master"
      - "base"

  - name: "gitlab.puppetlabs.demo"
    box: "puppetlabs/centos-6.5-64-nocm"
    roles: 
      - "gitlab_server"
      - "posix_agent"
      - "base"

  - name: "jenkins.puppetlabs.demo"
    box:  "puppetlabs/centos-6.5-64-nocm"
    roles: 
      - "jenkins_master"
      - "posix_agent"
      - "base"

  - name: "slave1.puppetlabs.demo"
    box: "puppetlabs/centos-6.5-64-nocm"
    roles: 
      - "jenkins_slave"
      - "posix_agent"
      - "base"
